- name: Ubuntu Workstation Setup
  hosts: localhost
  tasks:
    - include: tasks/apt.yml
    - include: tasks/gaming.yml
    - inclue: tasks/flatpak.yml
    - includ: tasks/homebrew.yml
    - include: tasks/podman.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvidia.yml
