- name: Home Setup
  hosts: localhost
  tasks:
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/gaming.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/homebrew.yml
    # - import_tasks: tasks/podman.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/ghostty.yml
    - import_tasks: tasks/nvidia.yml
    - import_tasks: tasks/nerd-font.yml
    - import_tasks: tasks/autocpu-freq.yml
    - import_tasks: tasks/cinnamon.yml
  tags:
    - home

- name: Work Setup
  hosts: localhost
  tasks:
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/ghostty.yml
    - import_tasks: tasks/nvidia.yml
    - import_tasks: tasks/nerd-font.yml
    - import_tasks: tasks/autocpu-freq.yml
    - import_tasks: tasks/cinnamon.yml
  tags:
    - work

- name: Work Setup
  hosts: localhost
  tasks:
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/dotfiles.yml
  tags:
    - wsl
