- name: Home Setup
  hosts: localhost
  tasks:
    - name: Load distribution variables
      ansible.builtin.include_vars:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"
      tags: always

    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/wine.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/flatpak-home.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/gpu.yml
    - import_tasks: tasks/nerd-font.yml
    - import_tasks: tasks/autocpu-freq.yml
    - import_tasks: tasks/cinnamon.yml
  tags:
    - home

- name: Work Setup
  hosts: localhost
  tasks:
    - name: Load distribution variables
      ansible.builtin.include_vars:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"
      tags: always

    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/gpu.yml
    - import_tasks: tasks/nerd-font.yml
    - import_tasks: tasks/autocpu-freq.yml
    - import_tasks: tasks/cinnamon.yml
  tags:
    - work

- name: WSL Setup
  hosts: localhost
  tasks:
    - name: Load distribution variables
      ansible.builtin.include_vars:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"
      tags: always

    - import_tasks: tasks/packages-wsl.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/dotfiles.yml
  tags:
    - wsl
