- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Install Rust compiler
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustc"
  when: cargo_exists is failed

- name: Check if Alacritty is already compiled
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/Documents/alacritty/target/release/alacritty"
  register: alacritty_binary_stat

- block:
  - name: Clone Alacritty
    ansible.builtin.git:
      repo: 'https://github.com/alacritty/alacritty.git'
      dest: "{{ lookup('env', 'HOME') }}/Documents/alacritty"
      version: master
    become: no

  - name: Compile Alacritty
    ansible.builtin.command:
      cmd: "cargo build --release"
      chdir: "{{ lookup('env', 'HOME') }}/Documents/alacritty"
    become: no

  - name: Copy Alacritty binary to /usr/local/bin
    ansible.builtin.copy:
      src: "{{ lookup('env', 'HOME') }}/Documents/alacritty/target/release/alacritty"
      dest: "/usr/local/bin/alacritty"
      mode: "0755"

  - name: Copy Alacritty logo to /usr/share/pixmaps
    ansible.builtin.copy:
      src: "{{ lookup('env', 'HOME') }}/Documents/alacritty/extra/logo/alacritty-term.svg"
      dest: "/usr/share/pixmaps/Alacritty.svg"
      mode: "0644"

  - name: Install Alacritty desktop file
    ansible.builtin.command:
      cmd: "desktop-file-install {{ lookup('env', 'HOME') }}/Documents/alacritty/extra/linux/Alacritty.desktop"
      creates: "/usr/share/applications/Alacritty.desktop"

  - name: Update desktop database
    ansible.builtin.command:
      cmd: "update-desktop-database"

  become: yes
  when: not alacritty_installed_stat.stat.exists
