- name: Clone Alacritty
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "{{ lookup('env', 'HOME') }}/Documents/alacritty"
    version: master

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Install rustup and Rust compiler
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | sh -- -y
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustc"
  register: rustup_result
  when: cargo_exists is failed

- name: Run cargo build --release
  ansible.builtin.command:
    cmd: "cargo build --release"
    chdir: "{{ lookup('env', 'HOME') }}/Documents/alacritty"
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/Documents/alacritty/.cargo/bin:{{ ansible_env.PATH }}"

- name: Copy Alacritty binary to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/Documents/alacritty/target/release/alacritty"
    dest: "/usr/local/bin/alacritty"
    mode: "0755"
  become: yes

- name: Copy Alacritty logo to /usr/share/pixmaps
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/Documents/alacritty/extra/logo/alacritty-term.svg"
    dest: "/usr/share/pixmaps/Alacritty.svg"
    mode: "0644"
  become: yes

- name: Install Alacritty desktop file
  ansible.builtin.command:
    cmd: "desktop-file-install {{ lookup('env', 'HOME') }}/Documents/alacritty/extra/linux/Alacritty.desktop"
    creates: "/usr/share/applications/Alacritty.desktop"
  become: yes

- name: Update desktop database
  ansible.builtin.command:
    cmd: "update-desktop-database"
  become: yes
