- name: Download autocpu-freq
  ansible.builtin.git:
    repo: 'https://github.com/AdnanHodzic/auto-cpufreq.git'
    dest: "{{ lookup('env', 'HOME') }}/Documents"
    version: master

- name: Install autocpu-freq
  become: true
  ansible.builtin.command:
    cmd: "sh auto-cpufreq-installer"
    chdir: "{{ lookup('env', 'HOME') }}/Documents/autocpu-freq"
