- name: Download autocpu-freq
  ansible.builtin.git:
    repo: 'https://github.com/AdnanHodzic/auto-cpufreq.git'
    dest: "{{ lookup('env', 'HOME') }}/Documents/auto-cpufreq"
    version: master

# - name: Install autocpu-freq
#   become: true
#   ansible.builtin.command:
#     cmd: "/bin/bash auto-cpufreq-installer"
#     chdir: "{{ lookup('env', 'HOME') }}/Documents/auto-cpufreq"
