- name: Check if cloned folder exists
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
  register: folder_stat

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/Tauromachian/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: main
  when: not folder_stat.stat.exists

- name: Remove default .bashrc
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: absent
  when: not folder_stat.stat.exists

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
    state: directory
    recurse: yes
    mode: '0755'

- name: Run stow for dotfiles
  ansible.builtin.shell:
    cmd: ./install.sh
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  args:
    executable: /bin/bash
  when: not folder_stat.stat.exists
