- name: Get Homebrew prefix
  become: false
  command: /home/linuxbrew/.linuxbrew/bin/brew --prefix
  register: brew_prefix
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Set fish path (Debian)
  ansible.builtin.set_fact:
    fish_path: "{{ brew_prefix.stdout }}/bin/fish"
  when: ansible_os_family == 'Debian'

- name: Set fish path (Arch)
  ansible.builtin.set_fact:
    fish_path: /usr/bin/fish
  when: ansible_os_family == 'Archlinux'

- name: Write fish path to allowed shells file
  become: true
  lineinfile:
    path: /etc/shells
    line: "{{ fish_path }}"
    insertafter: EOF
    state: present

- name: Set fish as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path }}"
