- name: Install Flatpak
  become: true
  apt:
    name: flatpak
    state: present

- name: Add Flathub remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo


- name: Install Work Flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - org.videolan.VLC
    - com.obsproject.Studio
    - org.shotcut.Shotcut
    - com.calibre_ebook.calibre
    - com.brave.Browser
    - com.usebruno.Bruno
    - org.mozilla.Thunderbird
    - it.mijorus.gearlever

- name: Install Home Flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
    - com.valvesoftware.Steam
    - org.telegram.desktop
    - com.discordapp.Discord
  tags:
    - home

- name: Give Brave access to home
  shell: |
    flatpak override --user com.brave.Browser --filesystem=home
  when: ansible_distribution == 'Ubuntu'

- name: Give Telegram access to home
  shell: |
    flatpak override --user org.telegram.desktop --filesystem=home
  when: ansible_distribution == 'Ubuntu'
  tags:
    - home

- name: Give Discord access to home
  shell: |
    flatpak override --user com.discordapp.Discord --filesystem=home
  when: ansible_distribution == 'Ubuntu'
  tags:
    - home

