- name: Add i386 architecture
  become: true
  command: dpkg --add-architecture i386

- name: Create directoy for keyrings
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and Install WineHQ GPG key
  become: true
  shell: |
    wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
  args:
    creates: /etc/apt/keyrings/winehq-archive.key
  register: gpg_key_result
  changed_when: gpg_key_result.rc == 0

- name: Add repository
  become: true
  shell: |
    wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
  args:
    creates: /etc/apt/sources.list.d/winehq-jammy.sources
  register: download_result
  changed_when: download_result.rc == 0

- name: Update cache
  become: true
  apt:
    update_cache: yes

- name: Install wine
  become: true
  apt:
    name: winehq-stable
    state: present
    install_recommends: yes
