- name: Ensure Homebrew dependencies are installed
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - git
      - tar
    state: present
  become: true

- name: Check if Homebrew is already installed
  ansible.builtin.stat:
    path: "/home/linuxbrew/.linuxbrew/bin/brew"
  register: brew_stat

- block:
  - name: Create Homebrew directory
    ansible.builtin.file:
      path: "/home/linuxbrew/.linuxbrew"
      state: directory
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      mode: '0755'
    become: true

  - name: Install Homebrew if not present
    ansible.builtin.shell: |
      curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /home/linuxbrew/.linuxbrew

  - name: Update Homebrew after install
    ansible.builtin.command: "/home/linuxbrew/.linuxbrew/bin/brew update"

  - name: Install Homebrew packages
    community.general.homebrew:
      name:
        - podman
        - podman-compose
        - neovim
        - starship
        - ripgrep
        - yt-dlp
        - lua
      state: present

  when: not brew_stat.stat.exists
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
