- name: Ensure Homebrew dependencies are installed
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - git
      - tar
    state: present
  become: true

- name: Check if Homebrew is already installed
  ansible.builtin.stat:
    path: "/home/linuxbrew/.linuxbrew/bin/brew"
  register: brew_stat

- name: Create Homebrew directory
  ansible.builtin.file:
    path: "/home/linuxbrew/.linuxbrew"
    state: directory
    mode: '0755'
  become: yes
  when: not brew_stat.stat.exists

- name: Change ownership of Homebrew directory to normal user
  ansible.builtin.file:
    path: "/home/linuxbrew/.linuxbrew"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: yes  # Still needs root to change ownership
  when: not brew_stat.stat.exists

- name: Install Homebrew if not present
  ansible.builtin.shell: |
    curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /home/linuxbrew/.linuxbrew
  become: false
  register: brew_install
  failed_when: brew_install.rc != 0
  when: not brew_stat.stat.exists

- block:
  - name: Update Homebrew after install
    ansible.builtin.command: "/home/linuxbrew/.linuxbrew/bin/brew update"
    become: false
    when: not brew_stat.stat.exists

  - name: Install Homebrew packages
    become: false
    community.general.homebrew:
      name:
        - podman
        - podman-compose
        - neovim
        - starship
        - ripgrep
        - yt-dlp
        - lua
      state: present

  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
