- name: Pull Podman images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop:
    - docker.io/library/alpine
    - docker.io/denoland/deno
    - docker.io/library/node:latest
    - docker.io/library/node:20-alpine
    - docker.io/library/node:18.20.4-alpine
    - nginx
    - docker.io/library/postgres
    - docker.io/valkey/valkey
    - php
    - docker.io/library/pgadmin
    - php:8.0-fpm-alpine
