- name: Install Ghostty (Debian)
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Ensure keyrings directory exists
      become: true
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Ghostty signing key
      become: true
      get_url:
        url: https://deb.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc
        dest: /tmp/deb.griffo.io.asc
        mode: "0644"

    - name: Install Ghostty keyring
      become: true
      command:
        argv:
          - gpg
          - --dearmor
          - --yes
          - -o
          - /etc/apt/keyrings/deb.griffo.io.gpg
          - /tmp/deb.griffo.io.asc
      args:
        creates: /etc/apt/keyrings/deb.griffo.io.gpg

    - name: Add Ghostty repository
      become: true
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/deb.griffo.io.gpg] https://deb.griffo.io/apt trixie main"
        filename: deb.griffo.io
        state: present

    - name: Update cache
      become: true
      apt:
        update_cache: yes

    - name: Install Ghostty
      become: true
      ansible.builtin.apt:
        name:
          - ghostty

- name: Install Ghostty (Arch)
  become: true
  community.general.pacman:
    name: ghostty
    state: present
  when: ansible_facts['os_family'] == 'Archlinux'
