- name: Check if ZSH is already installed
  ansible.builtin.stat:
    path: "/usr/bin/zsh"
  register: zsh_stat


- name: Install common packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
    state: present
  when: not zsh_stat.stat.exists

- name: Set default shell for user running ansible to zsh
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
